---
resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: ((concourse-git-url))
    branch: ((version-branch))
    file: "version"
    private_key: ((concourse-git-private-key))

- name: manifest
  type: git
  source:
    uri: ((concourse-git-url))
    branch: ((manifest-branch))
    paths:
    - "release-manifest.json"
    private_key: ((concourse-git-private-key))

- name: main
  type: git
  source:
    uri: ((concourse-git-url))
    branch: ((main-branch))
    private_key: ((concourse-git-private-key))

- name: stable
  type: git
  source:
    uri: ((concourse-git-url))
    branch: ((stable-branch))
    private_key: ((concourse-git-private-key))

- name: release
  type: git
  source:
    uri: ((concourse-git-url))
    branch: ((release-branch))
    private_key: ((concourse-git-private-key))

- name: release-base
  type: git
  source:
    uri: ((concourse-git-url))
    branch: ((release-branch))
    private_key: ((concourse-git-private-key))

jobs:
- name: start-release
  public: true
  serial_groups: [publish]
  plan:
  - get: manifest
    trigger: true
  - get: main
  - load_var: release-manifest
    file: "manifest/release-manifest.json"
    reveal: true
  - get: version
    params: {bump: ((.:release-manifest.release-level))}
  - task: start
    file: "main/ci/start/start.yml"
  - load_var: release-vars
    file: "release-vars/vars.json"
    reveal: true
  - put: version
    params: {bump: ((.:release-manifest.release-level))}
  - put: release-base
    params:
        repository: main
        branch: ((.:release-vars.release-branch-name))
  - set_pipeline: self
    file: "main/ci/pipeline.yml"
    vars:
        release-branch: ((.:release-vars.release-branch-name))
    var_files: ["main/ci/vars.yml"]

- name: prepare-release
  public: true
  serial_groups: [publish]
  plan:
  - get: release
    trigger: true
  - get: version
    params: {pre: rc}
  - task: unit
    file: "release/ci/unit/unit.yml"
  - task: prepare
    file: "release/ci/prepare/prepare.yml"
    vars:
        release-branch: "((release-branch))"
  - put: release
    params:
        repository: release
        only_tag: true
  - put: version
    params: {pre: rc}

- name: release
  public: true
  plan:
  - get: manifest
  - get: release
    passed: [prepare-release]
  - get: version
    passed: [prepare-release]
    params: {bump: final}
  - load_var: release-manifest
    file: "manifest/release-manifest.json"
    reveal: true
  - get: main
  - task: release
    file: "release/ci/release/release.yml"
    vars:
        release-branch: "((release-branch))"
        main-branch: "((main-branch))"
  - put: main
    params:
        repository: main
  - put: release
    params:
        repository: release
        only_tag: true
  - put: version
    params: {bump: final}

- name: update-stable
  public: true
  plan:
  - get: stable
  - get: release
    passed: [release]
    trigger: true
    params:
        fetch_tags: true
  - get: version
    passed: [release]
  - task: update-stable
    file: "release/ci/update/update.yml"
    vars:
        release-branch: "((release-branch))"
        stable-branch: "((stable-branch))"
  - put: stable
    params:
        repository: stable

- name: clean
  public: true
  plan:
  - get: release
    passed: [update-stable]
    trigger: true
    params:
        fetch_tags: true
  - get: version
    passed: [update-stable]
  - task: clean
    file: "release/ci/clean/clean.yml"
    vars:
        release-branch: "((release-branch))"
